export enum NewDebrieferSteps {
  NEW_DEBRIEFER = 'NEW_DEBRIEFER',
  SET_LICENSE = 'SET_LICENSE',
  SET_OWNER = 'SET_OWNER',
  SET_PRECREDITS = 'SET_PRECREDITS',
  SET_PRELINK = 'SET_PRELINK',
  COMPLETED = 'COMPLETED',
}
